services:
  ksmif-web-php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: php-fpm
    container_name: ksmif-web-php
    networks:
      - ksmif-web-net
      # - ksmif-mariadb-net
    volumes:
      - ksmif-web-data:/var/www/html
      - ./public/images:/var/www/html/public/images
      - ./storage/app/public:/var/www/html/storage/app/public
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: always

  ksmif-web-nginx:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: nginx
    container_name: ksmif-web-nginx
#    ports:
#      - "127.0.0.1:8080:80"
    networks:
      - ksmif-web-net
      # - rp-net
    volumes:
      - ksmif-web-data:/var/www/html:ro
      - ./public/images:/var/www/html/public/images:ro
      - ./storage/app/public:/var/www/html/storage/app/public:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - ksmif-web-php

volumes:
  ksmif-web-data:
    name: ksmif-web-data

networks:
  ksmif-web-net:
    name: ksmif-web-net
    driver: bridge
  # ksmif-mariadb-net:
  #   name: ksmif-mariadb-net
  #   external: true
  # rp-net:
  #   name: rp-net
  #   external: true
