services:
  ksmif-php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: php-fpm
    container_name: ksmif-php
    networks:
      - ksmif-net
      - mariadb-net
    volumes:
      - ksmif-data:/var/www/html
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: always

  ksmif-nginx:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: nginx
    container_name: ksmif-nginx
    ports:
      - "127.0.0.1:8080:80"
    networks:
      - ksmif-net
    volumes:
      - ksmif-data:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - ksmif-php

volumes:
  ksmif-data:
    name: ksmif-data

networks:
  ksmif-net:
    name: ksmif-net
    driver: bridge
  mariadb-net:
    name: mariadb-net
    external: true
